-- Run this SQL in Supabase SQL Editor.
-- It creates orders and order_items with RLS enabled.

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  phone text not null,
  address text not null,
  note text,
  total_amount numeric(12, 2) not null check (total_amount >= 0),
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  unit_price numeric(12, 2) not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0),
  line_total numeric(12, 2) not null check (line_total >= 0),
  created_at timestamptz not null default now()
);

create index if not exists idx_orders_created_at on public.orders(created_at desc);
create index if not exists idx_order_items_order_id on public.order_items(order_id);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- No anon/authenticated policies are added here.
-- Inserts are handled by server-side code using SUPABASE_SERVICE_ROLE_KEY.
